### ISSUE TITLE
m.taniguchi participates Github training

### ISSUE THREAD

**Issue by maabou512** [shu-mutou/github-sandbox#4]
- [ ] m.taniguchi has willing to participate Github training.
  - [ ] m.taniguchi can communicate with other contributors with respects.
  - [ ] Create `m.taniguchi.md`.

**Comment by atoato88** [comment]
oh, items are checked aleady!

**Comment by atoato88** [comment]
This checkbox will be checked by your hand if your PR merged.

**Comment by maabou512** [comment]
そういうことかｗ
